export const caseTypes = [
  { value: "Utang", label: "Utang" },
  { value: "Away Pamilya", label: "Away Pamilya" },
  { value: "Noise Complaint", label: "Noise Complaint" },
  { value: "Property Dispute", label: "Property Dispute" },
  { value: "Physical Injury", label: "Physical Injury" },
  { value: "Theft", label: "Theft" },
  { value: "Harassment", label: "Harassment" },
  { value: "Trespassing", label: "Trespassing" },
  { value: "Verbal Abuse", label: "Verbal Abuse" },
  { value: "Child Abuse", label: "Child Abuse" },
  { value: "Domestic Violence", label: "Domestic Violence" },
  { value: "Public Disturbance", label: "Public Disturbance" },
  { value: "Land Dispute", label: "Land Dispute" },
  { value: "Business Conflict", label: "Business Conflict" },
  { value: "Animal Complaint", label: "Animal Complaint" },
  { value: "Cyber Harassment", label: "Cyber Harassment" },
  { value: "Threats", label: "Threats" },
  { value: "Slander", label: "Slander" },
  { value: "Vandalism", label: "Vandalism" },
  { value: "Environmental Violation", label: "Environmental Violation" },
  { value: "Alcohol Related", label: "Alcohol Related" },
  { value: "Drug Related", label: "Drug Related" },
  { value: "Sexual Harassment", label: "Sexual Harassment" },
  { value: "Senior Citizen Abuse", label: "Senior Citizen Abuse" },
  { value: "Family Conflict", label: "Family Conflict" },
  { value: "Neighbor Dispute", label: "Neighbor Dispute" },
  { value: "Estafa", label: "Estafa" },
  { value: "Contract Violation", label: "Contract Violation" },
  { value: "Property Damage", label: "Property Damage" },
  { value: "Water Dispute", label: "Water Dispute" }
];
